version: '2'
services:
    clairesapp-app:
        image: clairesapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://clairesapp-mysql:3306/clairesapp?useUnicode=true&characterEncoding=utf8&useSSL=true
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    clairesapp-mysql:
        extends:
            file: mysql.yml
            service: clairesapp-mysql
